# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - name: Build package.
        run: npm run build
      - name: Release a "dev" tag version.
        if: 'github.event.release.prerelease'
        run: npm publish --tag dev
      - name: Release a "stable" tag version.
        if: '!github.event.release.prerelease'
        run: npm publish --tag latest
      
      
